import { useCallback, useRef } from 'react';

import { Printer } from 'lucide-react';

import { useAppStore } from '../store/useAppStore';
import DocumentRenderer from './ui/DocumentRenderer';

function exportRedactedPdf(redactedText: string, filename: string) {
  const win = window.open('', '_blank');
  if (!win) return;

  const escaped = redactedText
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n/g, '<br>')
    .replace(
      /\[([A-Z_]+)_(\d+)\]/g,
      '<span style="background:#1e3a5f;color:#93c5fd;border:1px solid #2563eb;' +
        'border-radius:3px;padding:0 4px;font-family:monospace;font-size:0.85em">' +
        '[$1_$2]</span>'
    );

  win.document.write(`<!DOCTYPE html><html><head>
    <title>Redacted — ${filename}</title>
    <style>
      body { font-family: Georgia, serif; font-size: 13px; line-height: 1.7;
             max-width: 760px; margin: 40px auto; color: #1a1a1a; }
      h1 { font-size: 16px; border-bottom: 1px solid #ccc; padding-bottom: 8px; }
      .meta { font-size: 11px; color: #666; margin-bottom: 24px; }
      .content { white-space: pre-wrap; }
      @media print { body { margin: 20px; } }
    </style>
  </head><body>
    <h1>Redacted Document — ${filename}</h1>
    <div class="meta">Generated by Securify · ${new Date().toLocaleString()} · All PII replaced with placeholders</div>
    <div class="content">${escaped}</div>
    <script>window.onload = () => { window.print(); }</script>
  </body></html>`);
  win.document.close();
}

export default function RedactedView() {
  const { doc } = useAppStore();
  if (!doc) return null;

  const originalRef = useRef<HTMLDivElement>(null);
  const redactedRef = useRef<HTMLDivElement>(null);
  const syncLockRef = useRef<'original' | 'redacted' | null>(null);

  const syncScroll = useCallback(
    (source: 'original' | 'redacted') => {
      if (syncLockRef.current && syncLockRef.current !== source) return;

      const sourceEl = source === 'original' ? originalRef.current : redactedRef.current;
      const targetEl = source === 'original' ? redactedRef.current : originalRef.current;
      if (!sourceEl || !targetEl) return;

      syncLockRef.current = source;
      targetEl.scrollTop = sourceEl.scrollTop;
      targetEl.scrollLeft = sourceEl.scrollLeft;

      requestAnimationFrame(() => {
        if (syncLockRef.current === source) {
          syncLockRef.current = null;
        }
      });
    },
    []
  );

  return (
    <div className="h-full min-h-0 flex flex-col px-8 py-6 gap-4 overflow-hidden">
      <div className="flex gap-5 flex-1 min-h-0 overflow-hidden">
        <div className="flex-1 flex flex-col min-w-0">
          <p className="section-label mb-2">Original document</p>
          <DocumentRenderer text={doc.original_text} scrollContainerRef={originalRef} onScroll={() => syncScroll('original')} />
        </div>

        <div className="flex-1 flex flex-col min-w-0">
          <div className="flex items-center justify-between mb-2">
            <p className="section-label">Redacted copy</p>
            <button
              onClick={() => exportRedactedPdf(doc.redacted_text, doc.filename)}
              className="flex items-center gap-1 text-[0.68rem] text-t3 hover:text-t1
                         transition-colors border border-border rounded-md px-2 py-0.5"
              title="Export redacted document as PDF"
            >
              <Printer size={11} />
              Export PDF
            </button>
          </div>
          <DocumentRenderer text={doc.redacted_text} redacted scrollContainerRef={redactedRef} onScroll={() => syncScroll('redacted')} />
        </div>
      </div>
    </div>
  );
}
